import { type PodcastEpisodesCall } from '../../models/ModelPodcastDetail';

export const LIST_EPISODES_INITIAL_STATE: PodcastEpisodesCall = {
	wrapperType: '',
	kind: '',
	artistId: 0,
	collectionId: 0,
	trackId: 0,
	artistName: '',
	collectionName: '',
	trackName: '',
	collectionCensoredName: '',
	trackCensoredName: '',
	artistViewUrl: '',
	collectionViewUrl: '',
	feedUrl: '',
	trackViewUrl: '',
	artworkUrl30: '',
	artworkUrl60: '',
	artworkUrl100: '',
	collectionPrice: 0,
	trackPrice: 0,
	collectionHdPrice: 0,
	releaseDate: '',
	collectionExplicitness: '',
	trackExplicitness: '',
	trackCount: 0,
	trackTimeMillis: 0,
	country: '',
	currency: '',
	primaryGenreName: '',
	contentAdvisoryRating: '',
	artworkUrl600: '',
	genreIds: [],
	genres: [],
};
